services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "1300:80"
        volumes:
            - ./app:/var/www/html
        depends_on:
            database:
                condition: service_healthy
        command: >
            bash -c "composer install --no-interaction --prefer-dist
            && apache2-foreground"

    database:
        image: mariadb
        restart: always
        volumes:
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_DATABASE: glad_blog
            MYSQL_ROOT_PASSWORD: password
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s

    adminer:
        image: adminer
        ports:
            - "1301:8080"
        depends_on:
            database:
                condition: service_healthy

    node:
        image: "node:8"
        user: "node"
        working_dir: /var/www/html
        environment:
            - NODE_ENV=production
        volumes:
            - ./app:/var/www/html
        command: >
            bash -c "npm install"

volumes:
    db_glad_blog:
